### ISSUE TITLE
Gnome 3 weird red X overlay on top of window close button

### ISSUE THREAD

**Issue by lagerspetz** [jcubic/Clarity#11]
I have a weird red X on top of window close button in Gnome 3 when I use Clarity as my theme, as shown in this screenshot:
http://imgur.com/4KKpKAL
It also happens with awOken, but does not happen on elementary or gnome or ambiance themes. Any ideas? Something to do with links?

**Comment by jcubic** [comment]
I'm using XFCE will try to install gnome 3 based distro on virtual box. Whick linux distro you're using (wanted to make sure I've got this error and don't install os for nothing).

**Comment by lagerspetz** [comment]
Hi, I just removed AwOken from the index.theme inherit list, and it fixes the problem. I wonder what in AwOken causes this.

**Comment by lagerspetz** [comment]
So to reproduce this, you probably need to have both AwOken and Clarity in your .themes and use gnome-tweak-tool in the gnome session to change the icon theme to Clarity.

**Comment by jcubic** [comment]
You can report the issue to awoken author, as for Clarity I can remove the Awoken from `Inherits` in `index.theme`. I've added this because Clarity was based on Awoken when it have gray mono icons by default and there were icons that was in Awoken that were not in Clarity.

**Comment by clenk** [comment]
Will a lot of other icons go missing if you remove it from Inherits?

**Comment by jcubic** [comment]
the icons will be taken from Humanity and gnome.

**Comment by lagerspetz** [comment]
I have not seen any icons disappear or change because of removing it. I feel it's not very necessary any more to inherit from AwOken.
