### ISSUE TITLE
symlink to blueberry-{active,disabled}.{svg,png} point to non-existing file

### ISSUE THREAD

**Issue by boenki** [jcubic/Clarity#12]
The icons are in "status", not in "apps" where the symlink points.

**Comment by jcubic** [comment]
thanks for the report fixed

**Comment by boenki** [comment]
They still point to non-existing files :(
I think it should be:
`blueberry-tray-disabled.svg scalable/status/blueberry-disabled.svg
blueberry-tray-active.svg scalable/status/blueberry-active.svg`

**Comment by jcubic** [comment]
Updated as you suggested didn't have time to actually check the files, maybe that app files was suppose to be generated in compound icons.
