### ISSUE TITLE
Releases on github

### ISSUE THREAD

**Issue by boenki** [jcubic/Clarity#13]
Hello,

would you please consider releasing your .tar.gz's here on github.

It's quite difficult to download them on gnome-look.org, especially using sripts.

I package Clarity for archlinux and  I always have problems with the files there.

Thank you

Steffen

**Comment by jcubic** [comment]
I've added few icons without releasing new version so I Will do this with next version that will be added as soon as I found some free time.

When I was adding files to gnome-look.org I didn't know that you can upload files on github.

**Comment by jcubic** [comment]
Also the tar.gz file on gnome-look.org is the same as the source code (with all the build files) maybe I should create tar.gz wihout those files include as someone suggested.

**Comment by jcubic** [comment]
https://github.com/jcubic/Clarity/releases/tag/0.4.7 it seem that for this version only blueberry icon, I din't have tags so I don't know which commits are included.

**Comment by jcubic** [comment]
It seems the the tar.gz file on gnome-look.org din't have all the files, I've forget that I've added tar.gz rule in Makefile that generate this file
