### ISSUE TITLE
Any reason for tarballing the symlinks vs reading the symlink to-do list from a text file?

### ISSUE THREAD

**Issue by ShadowKyogre** [jcubic/Clarity#9]
Was curious while I was poking around the source code to add a few symlinks for apps that don't have them yet (eg: engrampa)

**Comment by jcubic** [comment]
It's easier to upack the file then read the file and create symlinks on the fly.

**Comment by ShadowKyogre** [comment]
True. Just was asking since it makes contributing to the symlink list pretty awkward.

**Comment by jcubic** [comment]
I've put the symlinks in [src/symlinks](https://github.com/jcubic/Clarity/blob/master/src/symlinks) and [16x16-symlinks](https://github.com/jcubic/Clarity/blob/master/src/16x16-symlinks) and remove tarballs.

**Comment by jcubic** [comment]
Finally have found time to do this.
